[package]
name = "poker-of-ten-half"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
rand = "0.8.5"
# rand_core = "0.6"
# bevy_rand = { version = "0.7", features = ["rand_chacha", "wyrand"] }